server:
  port: 9001

spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/jpashop
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
      # show_sql: true
        format_sql: true
  message:
    basename: messages
  mvc:
    path match:
      matching-strategy: ant_path_matcher

logging.level:
  org.hibernate.SQL: debug

management:
  endpoints:
    web:
      exposure:
        include: '*'
